version: "3.8"

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - api
    ports:
      - "7800:7800"

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    restart: "no"
    image: api
    volumes:
      - ./api/:/usr/src/app
      - ./api/app-cache/:/usr/src/app/app-cache
    expose:
      - 8000