version: "3.8"

services:
  api:
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    container_name: api
    restart: "no"
    image: api
    volumes:
      - ./api/:/usr/src/app
      - ./api/app-cache/:/usr/src/app/app-cache
    ports:
      - "8000:8000"